### ISSUE TITLE
Refresh Token doesn't work

### ISSUE THREAD

**Issue by GuyKh** [GuyKh/py-iec-api#40]
### Checklist

- [x] The bug is reproducible against the latest release and/or `main`.
- [x] There are no similar issues or pull requests to fix it yet.

### Describe the bug
The JWT token is not getting renewed.
Manual calls to `client.refresh_token()` fail.

### To reproduce
Initiate the client, login and then call `client.refresh_token()`

### Expected behavior
Token would be refreshed

### Actual behavior
It doesn't

**Comment by idiamant** [comment]
Fixed the issue in PR #42 . 
client.refresh_token() works. 

After refresh it's expected to save the new token to file, for future use.
