### ISSUE TITLE
Error getting billing invoices

### ISSUE THREAD

**Issue by t0mer** [GuyKh/py-iec-api#47]
### Checklist

- [* ] The bug is reproducible against the latest release and/or `main`.
- [ *] There are no similar issues or pull requests to fix it yet.

### Describe the bug
I'm getting the following error while trying to retrieve the billing invoices:

    billings = self.client.get_billing_invoices()
  File "/usr/local/lib/python3.10/dist-packages/iec_api/iec_client.py", line 294, in get_billing_invoices
    return data.get_billing_invoices(self._token, bp_number, contract_id)
  File "/usr/local/lib/python3.10/dist-packages/iec_api/data.py", line 206, in get_billing_invoices
    return _get_response_with_descriptor(token, GET_BILLING_INVOICES.format(bp_number=bp_number,
  File "/usr/local/lib/python3.10/dist-packages/iec_api/data.py", line 72, in _get_response_with_descriptor
    raise IECError(login_error_response.code, login_error_response.error)
iec_api.models.exceptions.IECError: (Code 401): You're not authorized to this action!

### To reproduce

call the client.get_billing_invoices() function

### Expected behavior

Return list of invoices

### Actual behavior

Returning Error

**Comment by GuyKh** [comment]
Should be fixed in 0.1.6
